### ISSUE TITLE
Add Terms and conditions page

### ISSUE THREAD

**Issue by Neha** [jslovers/jslovers-branding-page#12]
We need to have community terms and conditions.

We can search for the content at open source communities - what they follow and we can use the same.

It would be a separate page

**Comment by sachin9164** [comment]
@Neha **Can I follow the below template?** if it is fine please assign this to me.

Community Terms and Conditions

Welcome to the JS lovers! We're thrilled to have you here. To ensure a safe, respectful, and collaborative environment, we ask all members to follow these terms and conditions:

1. Be Respectful: Treat all community members with respect and kindness. Harassment, discrimination, hate speech, or any form of offensive behavior will not be tolerated.

2. Inclusivity: We welcome individuals from all backgrounds and skill levels. Embrace diversity and help create an inclusive space where everyone feels valued.

3. Code of Conduct: We adhere to the principles outlined in our [Your Community Name] Code of Conduct. Please review it for a detailed explanation of our expected behavior.

4. Licensing: Respect intellectual property rights. When contributing to the community, ensure that your contributions comply with the applicable licenses and intellectual property rules.

5. Membership and Contributions: To become a member or contributor, follow the specified process outlined in our documentation. All contributions should be in line with our project's goals and guidelines.

6. Dispute Resolution: In case of conflicts or disputes, follow our designated dispute resolution process outlined in our Code of Conduct.

7. Privacy and Data Protection: We take your privacy seriously. Any personal information you share will be handled in accordance with our Privacy Policy.

8. Enforcement: Violation of these terms and conditions or our Code of Conduct may result in warnings, temporary suspensions, or permanent bans. The severity of enforcement will be determined on a case-by-case basis.

9. Communication Channels: Our primary communication channels are [list your communication channels, e.g., forums, mailing lists, chat platforms]. Please use these channels to engage with the community and share your thoughts and questions.

10. Updates: These terms and conditions may be updated periodically. Members will be notified of changes, and it's your responsibility to review them regularly.

By participating in the JSLovers, you agree to abide by these terms and conditions. If you have any questions or concerns, please reach out to our community administrators.

Thank you for being a part of our vibrant community!

JSLovers

**Comment by Neha** [comment]
Thank you @sachin9164 . Let me review the content

**Comment by sachin9164** [comment]
@Neha Review the content and let me know if changes are required.

Also please go through the design once  

<img width="1716" alt="Screenshot 2023-10-28 at 9 06 53 AM" src="https://github.com/jslovers/jslovers-branding-page/assets/39003367/1efa3204-7fbb-41fe-8440-e06f496f0f4b">

**Comment by Neha** [comment]
Thanks @sachin9164.


1. There should be no space between JS and Lovers. It should be JSLovers.
2. Please add some space between each point
3. Please raise the PR
